apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-server
  template:
    metadata:
      labels:
        app: sd-server
    spec:
      containers:
      - image: $SD_SERVER_IMAGE
        name: sd-server
        ports:
        - containerPort: 8080
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: sd-server-config
              key: TOPIC_NAME
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: sd-server-config
              key: REDIS_HOST
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: sd-server-config
              key: LOG_LEVEL                                   

---
apiVersion: v1
kind: Service
metadata:
  name: sd-server
spec:
  ports:
  - port: 7860
    protocol: TCP
    targetPort: 8080
  selector:
    app: sd-server
  type: LoadBalancer