---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-nfs-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /$FILESHARE_NAME
    server: $filestore_ip

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: filestore-nfs-pv
  resources:
    requests:
      storage: 1Ti

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-worker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion
  template:
    metadata:
      labels:
        app: stable-diffusion
    spec:
      volumes:
        - name: stable-diffusion-storage
          persistentVolumeClaim:
            claimName: sd
      containers:
      - name: stable-diffusion-webui
        image: asia-southeast1-docker.pkg.dev/speedy-victory-336109/singapore/sd-webui:inference
        readinessProbe:
          httpGet:
            path: /app_id
            port: 7860
          initialDelaySeconds: 10
          periodSeconds: 5        
        resources:
          limits:
            cpu: 2
            memory: 8Gi
            nvidia.com/gpu: 1
        ports:
          - containerPort: 7860
        volumeMounts:
          - mountPath: "/stable-diffusion-webui/models/Stable-diffusion"
            name: stable-diffusion-storage
            subPath: models/Stable-diffusion/sd15
          - mountPath: "/stable-diffusion-webui/outputs"
            name: stable-diffusion-storage
            subPath: outputs
          - mountPath: "/stable-diffusion-webui/models/ControlNet"
            name: stable-diffusion-storage
            subPath: models/ControlNet
      - name: sd-worker
        image: hellof20/sd-worker:v2
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /app_id
            port: 7860
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: sd-worker-config2
              key: PROJECT_ID
        - name: MODEL_NAME
          valueFrom:
            configMapKeyRef:
              name: sd-worker-config2
              key: MODEL_NAME
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: sd-worker-config2
              key: REDIS_HOST
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: sd-worker-config2
              key: LOG_LEVEL